"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql

revision = '0d25037dcc7f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('billing_type', sa.Enum('RECURRING', 'ONE_TIME', name='billingtype'), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='billfrequency'), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CASH', name='paymentmethod'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'COMPLETED', name='billstatus'), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_date', sa.Date(), nullable=False),
    sa.Column('conversation_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_date', name='unique_user_date')
    )
    op.create_index(op.f('ix_daily_conversations_conversation_date'), 'daily_conversations', ['conversation_date'], unique=False)
    op.create_index(op.f('ix_daily_conversations_user_id'), 'daily_conversations', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CTM_PROCESSING', 'CTM_SUCCESS', 'CTM_FAILED', 'MTC_PROCESSING', 'MTC_SUCCESS', 'MTC_FAILED', 'ATP_PROCESSING', 'ATP_SUCCESS', 'ATP_FAILED', 'BLP_PROCESSING', 'BLP_SUCCESS', 'BLP_FAILED', 'REVERSAL_PROCESSING', 'REVERSAL_SUCCESS', 'REVERSAL_FAILED', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('ctm_transaction_id', sa.String(), nullable=True),
    sa.Column('mtc_transaction_id', sa.String(), nullable=True),
    sa.Column('atp_transaction_id', sa.String(), nullable=True),
    sa.Column('blp_transaction_id', sa.String(), nullable=True),
    sa.Column('original_payment_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('network', sa.Enum('MTN', 'VOD', 'AIR', 'MAS', 'VIS', 'BNK', 'GOT', 'DST', 'MPP', 'VPP', 'STT', 'VBB', 'ABS', name='network'), nullable=True),
    sa.Column('ext_biller_ref_id', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('sender_provider', sa.String(), nullable=True),
    sa.Column('receiver_provider', sa.String(), nullable=True),
    sa.Column('date_paid', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_receipts_transaction_id'), 'receipts', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'ANNUALLY', name='billingperiod'), nullable=False),
    sa.Column('billing_period_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('agents', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('current_branch', sa.String(length=100), nullable=True),
    sa.Column('staff_id', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('organization_workplace', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('instagram_url', sa.String(length=200), nullable=True),
    sa.Column('profile_sharing', sa.Boolean(), nullable=True),
    sa.Column('in_app_notification', sa.Boolean(), nullable=True),
    sa.Column('sms_notification', sa.Boolean(), nullable=True),
    sa.Column('agents', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('customer_number', sa.String(length=20), nullable=False),
    sa.Column('network', sa.String(length=3), nullable=False),
    sa.Column('bank_code', sa.String(length=4), nullable=True),
    sa.Column('account_type', sa.Enum('MOBILE_MONEY', 'BANK_ACCOUNT', 'CARD', name='accounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.create_table('histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('data_plan', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_user_id'), 'histories', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ERROR', 'SUCCESS', 'PROMOTIONAL', 'TRANSACTIONAL', 'OTP', 'ALERT', name='notificationtype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'SENT', 'FAILED', 'DELIVERED', name='notificationstatus'), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('sms_phone', sa.String(), nullable=True),
    sa.Column('sms_message_id', sa.String(), nullable=True),
    sa.Column('sms_status', sa.String(), nullable=True),
    sa.Column('sms_delivery_status', sa.String(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sms_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('access_code', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gateway_response', sa.String(length=200), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_histories_user_id'), table_name='histories')
    op.drop_table('histories')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_transaction_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_table('payment')
    op.drop_table('otps')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_daily_conversations_user_id'), table_name='daily_conversations')
    op.drop_index(op.f('ix_daily_conversations_conversation_date'), table_name='daily_conversations')
    op.drop_table('daily_conversations')
    op.drop_table('billing')
    # ### end Alembic commands ###
