"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = '26976f26bf45'
down_revision = '73fe507a0e76'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_training_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('subfolder', sa.String(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_files_file_name'), 'ai_training_files', ['file_name'], unique=False)
    op.create_index(op.f('ix_ai_training_files_id'), 'ai_training_files', ['id'], unique=False)
    op.create_index(op.f('ix_ai_training_files_subfolder'), 'ai_training_files', ['subfolder'], unique=False)
    op.create_index(op.f('ix_ai_training_files_upload_timestamp'), 'ai_training_files', ['upload_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_training_files_user_id'), 'ai_training_files', ['user_id'], unique=False)
    op.add_column('files', sa.Column('subfolder', sa.String(), nullable=True))
    op.add_column('files', sa.Column('upload_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_files_subfolder'), 'files', ['subfolder'], unique=False)
    op.create_index(op.f('ix_files_upload_timestamp'), 'files', ['upload_timestamp'], unique=False)
    op.create_unique_constraint(None, 'receipts', ['id'])
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'social_accounts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_index(op.f('ix_files_upload_timestamp'), table_name='files')
    op.drop_index(op.f('ix_files_subfolder'), table_name='files')
    op.drop_column('files', 'upload_timestamp')
    op.drop_column('files', 'subfolder')
    op.drop_index(op.f('ix_ai_training_files_user_id'), table_name='ai_training_files')
    op.drop_index(op.f('ix_ai_training_files_upload_timestamp'), table_name='ai_training_files')
    op.drop_index(op.f('ix_ai_training_files_subfolder'), table_name='ai_training_files')
    op.drop_index(op.f('ix_ai_training_files_id'), table_name='ai_training_files')
    op.drop_index(op.f('ix_ai_training_files_file_name'), table_name='ai_training_files')
    op.drop_table('ai_training_files')
    # ### end Alembic commands ###
