"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = '496c14e889fc'
down_revision = '0d25037dcc7f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_conversations_conversation_date', table_name='daily_conversations')
    op.drop_index('ix_daily_conversations_user_id', table_name='daily_conversations')
    op.drop_table('daily_conversations')
    op.create_unique_constraint(None, 'receipts', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.create_table('daily_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conversation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('conversation_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_conversations_pkey'),
    sa.UniqueConstraint('user_id', 'conversation_date', name='unique_user_date')
    )
    op.create_index('ix_daily_conversations_user_id', 'daily_conversations', ['user_id'], unique=False)
    op.create_index('ix_daily_conversations_conversation_date', 'daily_conversations', ['conversation_date'], unique=False)
    # ### end Alembic commands ###
