"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = '8661f3ec1b82'
down_revision = '4f7d15caad45'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_accounts', type_='unique')
    # ### end Alembic commands ###
