"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = 'a8fe23c6fe7a'
down_revision = 'f2167469e782'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.String(length=2048), nullable=False))
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('condition', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('number_in_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('link', sa.String(length=2048), nullable=True))
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'attributes')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    op.drop_column('products', 'link')
    op.drop_column('products', 'number_in_stock')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'price')
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###
