"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = 'b6b72e9e06e4'
down_revision = '496c14e889fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_date', sa.Date(), nullable=False),
    sa.Column('conversation_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_date', name='unique_user_date')
    )
    op.create_index(op.f('ix_daily_conversations_conversation_date'), 'daily_conversations', ['conversation_date'], unique=False)
    op.create_index(op.f('ix_daily_conversations_user_id'), 'daily_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_conversations_user_id'), table_name='daily_conversations')
    op.drop_index(op.f('ix_daily_conversations_conversation_date'), table_name='daily_conversations')
    op.drop_table('daily_conversations')
    # ### end Alembic commands ###
