"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision = 'f06e171bc4a4'
down_revision = '001_pgvector'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_training_files', 'embedding',
               existing_type=Vector(dim=1536),
               comment='Vector embedding for semantic search',
               existing_comment='Vector embedding for semantic search (1536-dim for text-embedding-3-small)',
               existing_nullable=True)
    op.drop_index('ix_ai_training_files_embedding', table_name='ai_training_files')
    op.create_unique_constraint(None, 'receipts', ['id'])
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'social_accounts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.create_index('ix_ai_training_files_embedding', 'ai_training_files', ['embedding'], unique=False)
    op.alter_column('ai_training_files', 'embedding',
               existing_type=Vector(dim=1536),
               comment='Vector embedding for semantic search (1536-dim for text-embedding-3-small)',
               existing_comment='Vector embedding for semantic search',
               existing_nullable=True)
    # ### end Alembic commands ###
