"""Auto-generated migration script."""
from alembic import op
import sqlalchemy as sa

revision = 'f2167469e782'
down_revision = 'e1f6baa32369'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'receipts', ['id'])
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'social_accounts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    # ### end Alembic commands ###
