# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - lebe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Optional local build (you can remove this if not needed)
      - name: Create and start virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      # ---- NO ARTIFACT UPLOAD ANYMORE ----
      # ---- NO ARTIFACT DOWNLOAD ----
      # Everything is deployed directly from workspace ----

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A1F4E1A67B8646A098CE5293013E8364 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6C1CD8F274CA4B36B7528F8145D5D9E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9395B40356DC4E68B2C025783E28B3BD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lebe'
          slot-name: 'Production'
          package: '.'

          